### ISSUE TITLE
Serial does not exist

### ISSUE THREAD

**Issue by 2xAA** [MickMad/Teensy3-USBAudio#2]
Hi,

First of all - great work on this ^_^
This is very exciting stuff.

I'm trying to update the USB Audio board mode to work with the Audio library in Teensyduino to create a simple ADC audio input over USB.
I've updated the board descriptor file and I've got the playthru test working fine (I've not got the generated signals to work, in fact when using Teensyduino 1.26 those sketches are broken).

However, when trying to use the Audio library in USB Audio board mode, Serial cannot be accessed, which is a problem because in many of the files included by the Audio library, Serial is required.

I've tried adding Serial back in many different ways, but with no joy.

I assume there is a reason that Serial is disabled for this board mode, could you let me know why that is?
Would love to submit a PR at some point to update this to work with the Audio library in Teensyduino.

Thanks,
Sam

**Comment by MickMad** [comment]
Hi there,

sorry for the long delay. Unfortunately Serial and practically every other USB stuff is broken when using the USB Audio library because my lib. changes the USB packets word size and general size (standard is 64 X 1 byte, USB audio is 192 x 2 bytes) so that quite crashes everything else. The only thing I did not touch is USB control packet size. Right now I'm evaluating a way to move everything on the new teensyduino library which totally reorganized USB stuff. I'm also evaluating a way to integrate this in the Audio Library. Thanks anyway for the interest in the project. I'll keep you up-to-date.

Cheers,
Mick
